# Generated by Django 5.2.3 on 2025-07-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobs_attachments_alter_jobs_category_proposal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='owner',
        ),
        migrations.AlterField(
            model_name='proposal',
            name='submitted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='FreeLancer',
        ),
    ]
