# Generated by Django 5.2.3 on 2025-07-05 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='proposal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='jobs.proposal'),
        ),
    ]
