# Generated by Django 5.2.3 on 2025-07-05 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_conversation_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='proposal',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='jobs.proposal'),
            preserve_default=False,
        ),
    ]
