# Generated by Django 5.2.3 on 2025-07-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='message_attachments/'),
        ),
    ]
