# Generated by Django 5.2.3 on 2025-07-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_remove_message_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='message_attachments/'),
        ),
    ]
