# Generated by Django 5.2.3 on 2025-07-10 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_message_attachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='attachments',
        ),
    ]
