services:
  redis:
    image: redis
    container_name: redis
    ports: 
      - "6379:6379"
    
  django:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate "
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      - DB_NAME=freelancer
      - DB_USER=postgres
      - DB_PASSWORD=2511
      - DB_HOST=db 
      - DB_PORT=5432

  
  celery:
    build: .
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
  db:
    image: postgres
    shm_size: 128mb 
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: freelancer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2511
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "6543:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080 
  
  daphne:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 config.asgi:application
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - django
      - redis


volumes:
  postgres_data:
